version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: workplace-connect-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - workplace-network

  # MongoDB Express Web UI (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: workplace-connect-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - workplace-network

volumes:
  mongodb_data:
    name: workplace-connect-mongodb-data

networks:
  workplace-network:
    driver: bridge
